version: '3.9'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://myuser:mypassword@db/mydatabase
